version: '3.8'

services:
  rankcalculator1:
    build:
      context: ./RankCalculator
    ports:
      - "6000:80"
    environment:
      - DB_HOST=redis
      - DB_MAIN=redis_main:6379
      - DB_RU=redis_ru:6380
      - DB_EU=redis_eu:6381
      - DB_ASIA=redis_asia:6382
      - DB_PASSWORD=somePassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminPassword
      - RABBITMQ_PORT=5672
    depends_on:
      - redis_main
      - redis_ru
      - redis_eu
      - redis_asia
      - rabbitmq
    networks:
      - app-network

  rankcalculator2:
    build:
      context: ./RankCalculator
    ports:
      - "6001:80"
    environment:
      - DB_HOST=redis
      - DB_MAIN=redis_main:6379
      - DB_RU=redis_ru:6380
      - DB_EU=redis_eu:6381
      - DB_ASIA=redis_asia:6382
      - DB_PASSWORD=somePassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminPassword
      - RABBITMQ_PORT=5672
    depends_on:
      - redis_main
      - redis_ru
      - redis_eu
      - redis_asia
      - rabbitmq
    networks:
      - app-network

  valuator1:
    build:
      context: ./Valuator
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - DB_HOST=redis
      - DB_MAIN=redis_main:6379
      - DB_RU=redis_ru:6380
      - DB_EU=redis_eu:6381
      - DB_ASIA=redis_asia:6382
      - DB_PASSWORD=somePassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminPassword
    depends_on:
      - redis_main
      - redis_ru
      - redis_eu
      - redis_asia
      - rabbitmq
    networks:
      - app-network

  valuator2:
    build:
      context: ./Valuator
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - DB_HOST=redis
      - DB_MAIN=redis_main:6379
      - DB_RU=redis_ru:6380
      - DB_EU=redis_eu:6381
      - DB_ASIA=redis_asia:6382
      - DB_PASSWORD=somePassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminPassword
    depends_on:
      - redis_main
      - redis_ru
      - redis_eu
      - redis_asia
      - rabbitmq
    networks:
      - app-network

  valuator3:
    build:
      context: ./Valuator
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://+:5003
      - DB_HOST=redis
      - DB_MAIN=redis_main:6379
      - DB_RU=redis_ru:6380
      - DB_EU=redis_eu:6381
      - DB_ASIA=redis_asia:6382
      - DB_PASSWORD=somePassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminPassword
    depends_on:
      - redis_main
      - redis_ru
      - redis_eu
      - redis_asia
      - rabbitmq
    networks:
      - app-network

  valuator4:
    build:
      context: ./Valuator
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_URLS=http://+:5004
      - DB_HOST=redis
      - DB_MAIN=redis_main:6379
      - DB_RU=redis_ru:6380
      - DB_EU=redis_eu:6381
      - DB_ASIA=redis_asia:6382
      - DB_PASSWORD=somePassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminPassword
    depends_on:
      - redis_main
      - redis_ru
      - redis_eu
      - redis_asia
      - rabbitmq
    networks:
      - app-network
  
  eventslogger1:
    build:
      context: ./EventsLogger
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminPassword
    depends_on:
      - rabbitmq
    networks:
      - app-network

  eventslogger2:
    build:
      context: ./EventsLogger
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminPassword
    depends_on:
      - rabbitmq
    networks:
      - app-network

  redis_ru:
    image: "redis:alpine"
    command: redis-server --port 6380 --requirepass somePassword
    ports:
      - "6380:6380"
    networks:
      - app-network

  redis_eu:
    image: "redis:alpine"
    command: redis-server --port 6381 --requirepass somePassword
    ports:
      - "6381:6381"
    networks:
      - app-network

  redis_asia:
    image: "redis:alpine"
    command: redis-server --port 6382 --requirepass somePassword
    ports:
      - "6382:6382"
    networks:
      - app-network
  
  redis_main:
    image: "redis:alpine"
    command: redis-server --requirepass somePassword
    ports:
      - "6379:6379"
    networks:
      - app-network
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"
    depends_on:
      - valuator1
      - valuator2
      - valuator3
      - valuator4
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq-config/:/etc/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminPassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge