version: '3.8'

services:
  rankcalculator1:
    build:
      context: ./RankCalculator
    ports:
      - "6000:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=somePassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=adminPassword
      - RABBITMQ_PORT=5672
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  rankcalculator2:
    build:
      context: ./RankCalculator
    ports:
      - "6001:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=somePassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=adminPassword
      - RABBITMQ_PORT=5672
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  valuator1:
    build:
      context: ./Valuator
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  valuator2:
    build:
      context: ./Valuator
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://+:5002
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  valuator3:
    build:
      context: ./Valuator
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_URLS=http://+:5003
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  valuator4:
    build:
      context: ./Valuator
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_URLS=http://+:5004
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass somePassword
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"
    depends_on:
      - valuator1
      - valuator2
      - valuator3
      - valuator4
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4.0.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminPassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
